
services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      MONGODB_URI: mongodb://localhost:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
